name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci --silent
      - run: npm run build --if-present
      - run: npm test
      - run: rm -rf node_modules
      - run: npm install --only=production --silent
      - run: WORK_DIR=/apps/next-app
      - run: mkdir -p $WORK_DIR
      - run: rm -rf $WORK_DIR/{node_modules,.next,public,next.config.js,server.js}
      - run: mv -vf -t $WORK_DIR/ ./{node_modules,.next,public,next.config.js,server.js}
