name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Build app
        run: |
          npm ci --silent
          npm run build --if-present
          npm test
          rm -rf node_modules
          npm install --only=production --silent
      - name: Deploy files
        run: |
          mkdir -p /apps/next-app
          rm -rf /apps/next-app/{node_modules,.next,public,next.config.js,server.js}
          mv -vf -t /apps/next-app/ ./{node_modules,.next,public,next.config.js,server.js}
